# Generated by Django 5.1.1 on 2024-09-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
